### ISSUE TITLE
Issue with fof_subscription on upgrade

### ISSUE THREAD

**Issue by fluffy-critter** [thylacine/Feed-on-Feeds#7]
On SQLite I get the following error on install.php, after having merged from your fork after a while:

```
[1/1] Updating fof_subscription.subscription_added.column.add: Cannot upgrade table: [ALTER TABLE fof_subscription ADD subscription_added INTEGER DEFAULT '0' AFTER subscription_prefs]
SQLSTATE[HY000]: General error: 1 near "AFTER": syntax error
FAIL
```

Looks like this ALTER was added in commit 1da3ffd5, which looks like a handy feature so I'd like it to work. :) I'm not sure how to go about fixing it on my end though.

It seems like the AFTER thing is just for cosmetics in the schema and isn't supported by SQLite. Removing that clause on my installation appears to work fine.

**Comment by thylacine** [comment]
Ah, I was wrong, sqlite doesn't like AFTER at all, for the same reasons it can't drop or rename columns.  Fixed now.

**Comment by fluffy-critter** [comment]
Ah, a nice reminder of the 'lite' in SQLite. :)

Is there any particular reason for the AFTER aside from aesthetics?

**Comment by thylacine** [comment]
I can't come up with a technical reason off the top of my head, but it sticks in my mind that it could somehow make the ongoing ad-hoc schema-migration stuff faintly less nightmarish down the road if enough stuff gets added or reworked...

But, c'mon, aesthetic is a valid enough reason in my book. :)
